### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by xxyyyx** [Oreomeow/bili#12]
![QQ图片20211219031359](https://user-images.githubusercontent.com/42132468/146653206-bc0f87b5-079b-48bd-b329-23609600e970.png)
![QQ图片20211219031438](https://user-images.githubusercontent.com/42132468/146653208-34af58ef-9edd-4c81-a8ea-03e0acd81116.png)

**Comment by Oreomeow** [comment]
直接 Linux 依赖那里添加 `openjdk8`

**Comment by xxyyyx** [comment]
> 直接 Linux 依赖那里添加 `openjdk8`

可以了 谢谢
