### ISSUE TITLE
qinglong 配置

### ISSUE THREAD

**Issue by Marvll** [Oreomeow/bili#22]
当前版本:0
最新版本:2.1.3
有新版本，开始更新
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
正在解压文件.......
unzip: can't open BILIBILI-HELPER.zip[.zip]
cp: cannot stat './tmp/BILIBILI-HELPER*.jar': No such file or directory
配置文件不存在。
cp: cannot stat './tmp/config.json': No such file or directory
清除缓存.........
更新完成
没找到BILIBILI-HELPER.jar，开始下载..........
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
正在解压文件.......
unzip: can't open BILIBILI-HELPER.zip[.zip]
cp: cannot stat './tmp/BILIBILI-HELPER*.jar': No such file or directory
配置文件不存在。
cp: cannot stat './tmp/config.json': No such file or directory
清除缓存.........
更新完成
配置文件路径:/ql/config/java_conf.json
Error: Unable to access jarfile BILIBILI-HELPER.jar

## 执行结束... 2022-03-04 12:43:04 耗时 2 秒

**Comment by Oreomeow** [comment]
没下载成功，提供一下你的运行设备信息

**Comment by Marvll** [comment]
root@qinglong:/ql $ ql raw https://raw.githubusercontent.com/Oreomeow/bili/main/bilibili_helper.sh
## 开始执行... 2022-03-04 21:43:03


--------------------------------------------------------------

开始下载：https://raw.githubusercontent.com/Oreomeow/bili/main/bilibili_helper.sh 

保存路径：/ql/raw/main_bilibili_helper.sh

下载 main_bilibili_helper.sh 成功...

Bilibili 助手 -> 添加成功

加载sendNotify，当前版本: 20220302
检测到一对一Uid文件WxPusherUid.json，载入...
检测到显示备注名称，格式为: 京东别名(备注)
开始发送通知...
通知标题: 脚本任务更新
sendNotify正在处理账号Remark.....
处理完成，开始发送通知...

## 执行结束... 2022-03-04 21:43:06  耗时 3 秒
root@qinglong:/ql $ task raw_main_bilibili_helper.sh
## 开始执行... 2022-03-04 21:44:50


# 当前总共 3 个 JD_COOKIE。

当前版本:2.1.3
最新版本:2.1.3
已经是最新版本，不需要更新！！！
没找到BILIBILI-HELPER.jar，开始下载..........
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
正在解压文件.......
unzip: can't open BILIBILI-HELPER.zip[.zip]
cp: cannot stat './tmp/BILIBILI-HELPER*.jar': No such file or directory
配置文件不存在。
cp: cannot stat './tmp/config.json': No such file or directory
清除缓存.........
更新完成
配置文件路径:/ql/config/java_conf.json
Error: Unable to access jarfile BILIBILI-HELPER.jar

## 执行结束... 2022-03-04 21:44:53 耗时 3 秒
root@qinglong:/ql $

**Comment by Oreomeow** [comment]
已更新
