### ISSUE TITLE
青龙面板安装了依赖还是提示缺少依赖

### ISSUE THREAD

**Issue by zekohung** [Oreomeow/bili#23]
![微信截图_20220317102204](https://user-images.githubusercontent.com/18080829/158723818-4351c6d1-0a34-4dad-9300-09e150ee8230.png)
![微信截图_20220317102238](https://user-images.githubusercontent.com/18080829/158723821-229a9815-90c8-41eb-b754-8dae37377b35.png)

**Comment by Oreomeow** [comment]
#12
