### ISSUE TITLE
设置变量BILIBILI_COOKIE提示失效

### ISSUE THREAD

**Issue by anzhefun** [Oreomeow/bili#63]
在青龙中变量BILIBILI_COOKIE失效，但是cookie是刚刚抓取的
2022-12-12 15:56:16.432 WARN  t.m.t.UserCheck - Cookies可能失效了,请仔细检查配置中的Cookies是否有效

**Comment by night-raise** [comment]
检查有没有特殊符号什么的需要转义？
或者退出重新登陆抓一下。

**Comment by anzhefun** [comment]
看了一下貌似，原始的没有转译问题
另外这个key是退出后重新抓取的，所以也不知道为什么是这样的错误
不好意思，不太会用github就直接好像不小心关闭了问题
